### PR TITLE
Update to go 1.21 and update sdk v2 version to fix compilation error

### PR DESCRIPTION
**Pull request by henryrecker-pingidentity**

### CODE REVIEW

**Comment by henryrecker-pingidentity** [comment]
This pull request is waiting on https://github.com/github/roadmap/issues/806 to allow CodeQL to build with Go 1.21

**Review by wesleymccollam — APPROVED** [review]
